### PR TITLE
Fixed some issues.

### PR DESCRIPTION
**Pull request by stuartjdouglas**
for @YagoCarballo

### CODE REVIEW

**Comment by YagoCarballo** [comment]
:+1:

**Comment by jslvtr** [comment]
The changes I introduced made it simpler (both changes in project.js). We should keep them.

**Comment by YagoCarballo** [comment]
changes?

**Comment by jslvtr** [comment]
Ideally everything coming through the URL should be using `decodeURIComponent`.

The rest of the changes were good though, don't scrap them.

**Comment by stuartjdouglas** [comment]
did you remove the replacing of spaces to _ ?

**Comment by jslvtr** [comment]
Yeah, I did. Does it have to be _?

**Pull request closed without merging**
