### PR TITLE
Implemented querying, this when used with the endpoint /run/:token will ...

### PR DESCRIPTION
**Pull request by stuartjdouglas**
...query the destination and reply with the raw unaltered response.

### CODE REVIEW

**Comment by stuartjdouglas** [comment]
Logs will return information about the defined endpoint

**Comment by jslvtr** [comment]
Looks good to me!

**Comment by YagoCarballo** [comment]
:+1:

**Comment by stuartjdouglas** [comment]
We may come back to this when the client side is implemented, but all should work

**Pull request closed without merging**
